# awesome-media-config
server:
  port: 8090

management:
  security:
    enabled: false    

promotion: action

# inmemory 접속 
spring:
  datasource:    
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mediadb;
    username: sa
    passworld: null
    
    
  h2:
    console:
      enabled: true
    
#  logging:
#      file: log/spring.log
    
    
    
    
